import type { Metadata } from "next";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";
import "@mantine/core/styles.css";
import "./globals.css";
import ReduxWrapper from "@/components/ReduxWrapper";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Wrapped with suspense, to tackle Cypress test hydration error
          caused by cypress itself trying to find its injected script in the head tag
          but instead got ours
        */}
        <Suspense>
          <ColorSchemeScript />
        </Suspense>
      </head>
      <body>
        <MantineProvider>
          <ReduxWrapper>{children}</ReduxWrapper>
        </MantineProvider>
      </body>
    </html>
  );
}
